# Generated by Django 2.2.3 on 2019-07-19 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20, unique=True)),
                ('priority', models.IntegerField(choices=[(1, 'Minimum'), (2, 'Low'), (3, 'Average'), (4, 'High'), (5, 'Maxiumum')], default=3)),
                ('metaData', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.MetaData')),
            ],
            options={
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('hometown', models.TextField(blank=True, default='')),
                ('bandcamp', models.URLField(blank=True, default='')),
                ('bandcamp_embed_code', models.TextField(blank=True, default='')),
                ('soundcloud_embed_code', models.TextField(blank=True, default='')),
                ('youtube_embed_code', models.TextField(blank=True, default='')),
                ('youtube', models.URLField(blank=True, default='')),
                ('facebook', models.URLField(blank=True, default='')),
                ('soundcloud', models.URLField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('priority', models.IntegerField(choices=[(1, 'Minimum'), (2, 'Low'), (3, 'Average'), (4, 'High'), (5, 'Maxiumum')], default=3)),
                ('genres', models.ManyToManyField(blank=True, to='music.Genre')),
                ('metaData', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.MetaData')),
            ],
            options={
                'ordering': ['priority', 'metaData__posted_on', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('cover_image', models.ImageField(blank=True, upload_to='')),
                ('bandcamp_embed_code', models.TextField(blank=True, default='')),
                ('youtube_embed_code', models.TextField(blank=True, default='')),
                ('bandcamp', models.URLField(blank=True, default='')),
                ('youtube', models.URLField(blank=True, default='')),
                ('release_date', models.DateField(blank=True, default=None, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('priority', models.IntegerField(choices=[(1, 'Minimum'), (2, 'Low'), (3, 'Average'), (4, 'High'), (5, 'Maxiumum')], default=3)),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albums', to='music.Artist')),
                ('genres', models.ManyToManyField(blank=True, to='music.Genre')),
                ('metaData', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.MetaData')),
            ],
            options={
                'ordering': ['priority', 'artist', 'name'],
            },
        ),
    ]
