# Generated by Django 2.2.3 on 2019-07-19 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='meta_data',
            new_name='metaData',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='meta_data',
            new_name='metaData',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='meta_data',
            new_name='metaData',
        ),
    ]
