# Generated by Django 2.2.3 on 2019-07-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='band_camp',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='album',
            name='youtube',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='band',
            name='band_camp',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='band',
            name='facebook',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='band',
            name='genres',
            field=models.ManyToManyField(blank=True, to='music.Genre'),
        ),
        migrations.AlterField(
            model_name='band',
            name='home_town',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='band',
            name='soundcloud',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='band',
            name='youtube',
            field=models.URLField(blank=True, default=''),
        ),
    ]
