# Generated by Django 2.2.3 on 2019-07-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genres',
            field=models.ManyToManyField(blank=True, to='music.Genre'),
        ),
        migrations.AlterField(
            model_name='album',
            name='songs',
            field=models.ManyToManyField(blank=True, to='music.Song'),
        ),
        migrations.AlterField(
            model_name='band',
            name='albums',
            field=models.ManyToManyField(blank=True, to='music.Album'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='sub_genres',
            field=models.ManyToManyField(blank=True, related_name='_genre_sub_genres_+', to='music.Genre'),
        ),
        migrations.AlterField(
            model_name='song',
            name='genres',
            field=models.ManyToManyField(blank=True, to='music.Genre'),
        ),
    ]
