# Generated by Django 2.2.3 on 2019-07-02 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20190702_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='band_camp',
            new_name='bandcamp',
        ),
        migrations.RenameField(
            model_name='band',
            old_name='band_camp',
            new_name='bandcamp',
        ),
        migrations.RenameField(
            model_name='band',
            old_name='home_town',
            new_name='hometown',
        ),
    ]
