# Generated by Django 2.2.3 on 2019-07-31 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20190720_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.TextField(default='', max_length=20, unique=True),
        ),
    ]
