# Generated by Django 2.2.3 on 2019-07-31 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20190731_0140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['-priority', 'name']},
        ),
        migrations.AddField(
            model_name='genre',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
