# Generated by Django 2.2.3 on 2019-07-31 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20190731_0211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['priority', 'name']},
        ),
    ]
