# Generated by Django 2.2.3 on 2019-07-03 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20190703_0049'),
        ('shows', '0004_auto_20190703_0049'),
        ('media', '0006_auto_20190703_0049'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Band',
        ),
        migrations.AddField(
            model_name='artist',
            name='genres',
            field=models.ManyToManyField(blank=True, to='music.Genre'),
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albums', to='music.Artist'),
        ),
    ]
