# Generated by Django 2.2.3 on 2019-07-03 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_auto_20190703_0408'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='bandcampEmbedCode',
            field=models.TextField(blank=True, default=''),
        ),
    ]
