# Generated by Django 2.2.3 on 2019-07-07 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_artist_bandcampembedcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='bandcampEmbedCode',
        ),
    ]
