# Generated by Django 2.2.3 on 2019-07-07 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_remove_artist_bandcampembedcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='sub_genres',
        ),
    ]
