# Generated by Django 2.2.3 on 2019-07-07 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_remove_genre_sub_genres'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Song',
        ),
    ]
