# Generated by Django 2.2.3 on 2019-07-11 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_auto_20190709_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='bandcamp_embed_code',
            field=models.TextField(blank=True, default=''),
        ),
    ]
