# Generated by Django 2.2.3 on 2019-07-11 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_album_bandcamp_embed_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='bandcamp_embed_code',
            field=models.TextField(blank=True, default=''),
        ),
    ]
