# Generated by Django 2.2.3 on 2019-07-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0015_artist_soundcloud_embed_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='youtube_embed_code',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='artist',
            name='youtube_embed_code',
            field=models.TextField(blank=True, default=''),
        ),
    ]
