# Generated by Django 2.2.3 on 2019-07-28 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='permission_to_contact',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
