# Generated by Django 2.2.3 on 2019-07-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_upload',
            field=models.BooleanField(default=False),
        ),
    ]
