# Generated by Django 2.2.3 on 2019-07-02 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_can_upload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
