# Generated by Django 2.2.3 on 2019-07-19 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.TextField(default='')),
                ('posted_on', models.DateField(default=django.utils.timezone.now)),
                ('last_updated_on', models.DateField()),
                ('last_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meta_data_edits', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meta_data_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
