# Generated by Django 2.2.3 on 2019-07-02 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('text', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Directions',
            fields=[
                ('infopage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='info.InfoPage')),
                ('starting_point', models.TextField(default='')),
            ],
            bases=('info.infopage',),
        ),
    ]
