# Generated by Django 2.2.3 on 2019-07-19 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        ('media', '__first__'),
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.TextField(choices=[('about', 'About'), ('contact', 'Contact')], default='about')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_caption', models.TextField(blank=True, null=True)),
                ('title', models.TextField(default='')),
                ('text', models.TextField(default='')),
                ('priority', models.IntegerField(choices=[(1, 'Minimum'), (2, 'Low'), (3, 'Average'), (4, 'High'), (5, 'Maxiumum')], default=3)),
                ('meta_data', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.MetaData')),
            ],
            options={
                'ordering': ['priority', 'metadata__posted_on', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Directions',
            fields=[
                ('infopage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='info.InfoPage')),
                ('starting_point', models.TextField(blank=True, default='')),
            ],
            bases=('info.infopage',),
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('infopage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='info.InfoPage')),
                ('start_or_primary_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('approximate_date', models.BooleanField()),
                ('artists', models.ManyToManyField(blank=True, to='music.Artist')),
                ('fliers', models.ManyToManyField(blank=True, max_length=2, to='media.Flier')),
                ('photos', models.ManyToManyField(blank=True, max_length=2, to='media.Photo')),
            ],
            bases=('info.infopage',),
        ),
    ]
