# Generated by Django 2.2.3 on 2019-07-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directions',
            name='starting_point',
            field=models.TextField(blank=True, default=''),
        ),
    ]
