# Generated by Django 2.2.3 on 2019-07-19 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='flier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media.Flier'),
        ),
        migrations.AddField(
            model_name='history',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media.Photo'),
        ),
        migrations.AddField(
            model_name='history',
            name='youtube_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media.YoutubeVideo'),
        ),
        migrations.AlterField(
            model_name='history',
            name='start_or_primary_date',
            field=models.DateField(),
        ),
    ]
