# Generated by Django 2.2.3 on 2019-07-31 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20190720_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infopage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='infopage',
            name='image_caption',
        ),
    ]
