# Generated by Django 2.2.3 on 2019-07-02 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_infopage_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='infopage',
            name='image_caption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
