# Generated by Django 2.2.3 on 2019-07-31 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_auto_20190731_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infopage',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
