# Generated by Django 2.2.3 on 2019-08-04 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_auto_20190731_2334'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Directions',
        ),
    ]
