# Generated by Django 2.2.3 on 2019-07-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField(default='08:00')),
                ('suggested_donation', models.IntegerField(default=7)),
                ('facebook', models.TextField(default='')),
                ('bands', models.ManyToManyField(to='music.Band')),
                ('genres', models.ManyToManyField(blank=True, to='music.Genre')),
            ],
        ),
    ]
