# Generated by Django 2.2.3 on 2019-07-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='facebook',
            field=models.TextField(blank=True, default=''),
        ),
    ]
