# Generated by Django 2.2.3 on 2019-07-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_auto_20190702_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='facebook',
            field=models.URLField(blank=True, default=''),
        ),
    ]
