# Generated by Django 2.2.3 on 2019-08-12 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_auto_20190720_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='cancelled',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
