# Generated by Django 2.2.3 on 2019-07-03 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20190703_0049'),
        ('shows', '0003_auto_20190702_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='bands',
        ),
        migrations.AddField(
            model_name='show',
            name='artists',
            field=models.ManyToManyField(to='music.Artist'),
        ),
    ]
