# Generated by Django 2.2.3 on 2019-07-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0005_show_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='instagram',
            field=models.URLField(blank=True, default=''),
        ),
    ]
