# Generated by Django 2.2.3 on 2019-07-09 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0006_show_instagram'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='show',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='show',
            name='suggested_donation_max',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
