# Generated by Django 2.2.3 on 2019-07-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='caption',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='caption',
            field=models.TextField(blank=True, default=''),
        ),
    ]
