# Generated by Django 2.2.3 on 2019-07-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubevideo',
            name='bands',
            field=models.ManyToManyField(blank=True, to='music.Band'),
        ),
    ]
