# Generated by Django 2.2.3 on 2019-07-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_auto_20190702_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubevideo',
            name='youtube_url',
            field=models.URLField(),
        ),
    ]
