# Generated by Django 2.2.3 on 2019-07-03 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_auto_20190702_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='band',
        ),
        migrations.RemoveField(
            model_name='youtubevideo',
            name='bands',
        ),
    ]
