# Generated by Django 2.2.3 on 2019-08-04 19:27

from django.db import migrations, models
import media.models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_auto_20190801_0143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='youtubevideo',
            options={'ordering': ['priority', '-metaData__posted_on', 'show', 'artist']},
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='youtube_url',
            field=models.URLField(validators=[media.models.validate_youtube_url]),
        ),
    ]
