# Generated by Django 2.2.3 on 2019-07-03 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20190703_0049'),
        ('media', '0005_auto_20190703_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='music.Artist'),
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='music.Artist'),
        ),
    ]
