# Generated by Django 2.2.3 on 2019-08-12 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0006_auto_20190804_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flier',
            name='show',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flier', to='shows.Show'),
        ),
    ]
